language: node_js
node_js:
  - "10.14"
cache:
  directories:
    - node_modules
before_install:
  - cd frontend
  - mv ./src/config.example ./src/config
install:
  - npm install
script:
  - npm run build
  - npm run deploy
  - npm run invalidate
branches:
  only:
    - master
