language: node_js
node_js:
  - "10.14"
cache: npm
before_install:
  - cd frontend
  - mv ./src/config.example ./src/config
install:
  - npm install
script:
  - npm run build
branches:
  only:
    - master
